# Stage 1: Builder
FROM golang:1.23.3-alpine AS builder

# Set working directory
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

# Stage 2: Production
FROM alpine:latest

# Set working directory
WORKDIR /root/

# Copy the pre-built binary file from builder stage
COPY --from=builder /app/main .

# Expose port
EXPOSE 4000

# Command to run the executable
CMD ["./main"]